# name: Terraform CI

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# permissions:
#   contents: read

# jobs:
#   terraform-dev:
#     name: Terraform Dev
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Authenticate with Google Cloud (Dev)
#         uses: google-github-actions/auth@v1
#         with:
#           credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_DEV }}

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v1

#       - name: Ensure modules are downloaded
#         run: terraform get
#         working-directory: terraform/environments/dev

#       - name: Initialize Terraform
#         run: terraform init
#         working-directory: terraform/environments/dev

#       - name: Plan Terraform changes
#         run: terraform plan -var-file="terraform.tfvars" -out=tfplan
#         working-directory: terraform/environments/dev

#       - name: Apply Terraform changes
#         run: terraform apply -auto-approve tfplan
#         working-directory: terraform/environments/dev

#   terraform-prod:
#     name: Terraform Prod
#     runs-on: ubuntu-latest
#     needs: terraform-dev

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Authenticate with Google Cloud (Prod)
#         uses: google-github-actions/auth@v1
#         with:
#           credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_PROD }}

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v1

#       - name: Ensure modules are downloaded
#         run: terraform get
#         working-directory: terraform/environments/prod


#       - name: Initialize Terraform
#         run: terraform init
#         working-directory: terraform/environments/prod

#       - name: Plan Terraform changes
#         run: terraform plan -var-file="terraform.tfvars" -out=tfplan
#         working-directory: terraform/environments/prod

#       - name: Apply Terraform changes
#         run: terraform apply -auto-approve tfplan
#         working-directory: terraform/environments/prod
